# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='fullname',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
