# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20170630_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='is_readlater',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='is_saved',
        ),
    ]
