# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20170630_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.User')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.User')),
            ],
        ),
    ]
